export type Post = {
  slug: string;
  title: string;
  excerpt: string;
  metaDescription: string;
  city?: string;
  citySlug?: string;
  service?: string;
  serviceSlug?: string;
  publishedAt: string;
  readMinutes: number;
  body: Array<
    | { type: "p"; text: string }
    | { type: "h2"; text: string }
    | { type: "h3"; text: string }
    | { type: "ul"; items: string[] }
  >;
};

export const POSTS: Post[] = [
  {
    slug: "frozen-pipes-welland-prevention",
    title: "Frozen Pipes in Welland: How to Prevent Them (and What to Do if They Burst)",
    excerpt: "Welland winters can drop fast. Here's exactly how local homeowners can prevent frozen pipes — and what to do if it's already too late.",
    metaDescription: "Frozen pipes in Welland, ON? Learn how to prevent and thaw them safely, plus when to call an emergency plumber. Local advice from Ottr Plumr.",
    city: "Welland",
    citySlug: "welland",
    service: "Repairs & Diagnostics",
    serviceSlug: "repairs-diagnostics",
    publishedAt: "2025-11-12",
    readMinutes: 6,
    body: [
      { type: "p", text: "If you've lived through a Welland winter, you already know — when the wind whips off the canal and overnight temperatures plunge into the negatives, exposed pipes become a real liability. Frozen pipes are one of the most common emergency calls we get across the Niagara Region, and they're almost always preventable." },
      { type: "h2", text: "Why Welland homes are especially at risk" },
      { type: "p", text: "Welland's older neighbourhoods like Crowland, Dain City, and Cooks Mills have plenty of homes built before modern insulation standards. Crawlspaces, unheated basements, and exterior wall plumbing runs are common — and those are exactly the spots that freeze first when the temperature drops below -10°C." },
      { type: "h2", text: "5 prevention steps every Welland homeowner should take" },
      { type: "ul", items: ["Insulate any exposed pipes in basements, crawlspaces, attics, and garages with foam pipe sleeves.", "On extreme cold nights, let one or two faucets drip — moving water resists freezing.", "Open kitchen and bathroom cabinet doors so warm air reaches plumbing on exterior walls.", "Disconnect garden hoses and shut off the interior valves to outdoor spigots before the first hard freeze.", "Keep your thermostat at 18°C (65°F) or higher overnight — even if you're away."] },
      { type: "h2", text: "What to do if a pipe freezes" },
      { type: "p", text: "If you turn on a tap and only get a trickle, suspect a freeze. Shut off your main water valve immediately — if the pipe has cracked, you want to limit the damage when it thaws. Then call a licensed plumber. Never use an open flame to thaw a pipe; we use safe heating cables and warm towels to thaw without splitting the line." },
      { type: "h2", text: "Burst pipe? Call us 24/7" },
      { type: "p", text: "If you're already standing in water, every minute matters. Ottr Plumr runs 24/7 emergency service across Welland and the entire Niagara Region. Call 289-488-1007 — we'll dispatch fast and stop the damage." },
    ],
  },
  {
    slug: "tankless-vs-tank-water-heater-niagara",
    title: "Tankless vs Tank Water Heater in Niagara: Which Should You Choose?",
    excerpt: "Tankless water heaters get all the hype, but they're not always the right call. Here's our honest, Niagara-specific breakdown.",
    metaDescription: "Tankless vs tank water heater in the Niagara Region — costs, lifespan, and which makes sense for your home. Honest advice from Ottr Plumr.",
    city: "Niagara Region",
    service: "Water Heaters",
    serviceSlug: "water-heaters",
    publishedAt: "2025-11-05",
    readMinutes: 7,
    body: [
      { type: "p", text: "We get this question on almost every water heater replacement quote in St. Catharines, Niagara Falls, and Welland: \"Should I switch to tankless?\" The honest answer is — it depends. Here's a no-nonsense breakdown to help you decide before your old tank lets go in the middle of a shower." },
      { type: "h2", text: "How each system works" },
      { type: "h3", text: "Conventional tank" },
      { type: "p", text: "A tank water heater stores 40–75 gallons of pre-heated water, ready to go. When you draw hot water, the tank refills and reheats. Simple, proven, affordable — but you're heating water 24/7 even when you don't use it." },
      { type: "h3", text: "Tankless (on-demand)" },
      { type: "p", text: "A tankless unit fires up only when you turn on a hot tap, heating water as it flows through. No standby losses, smaller footprint, longer lifespan — but a higher upfront cost and sometimes a need for upgraded gas lines or venting." },
      { type: "h2", text: "Cost comparison (Niagara averages)" },
      { type: "ul", items: ["Tank install: typically $1,800–$2,800 supplied and installed.", "Tankless install: typically $4,500–$6,500 depending on gas, venting, and electrical upgrades.", "Tank lifespan: 8–12 years.", "Tankless lifespan: 18–22 years with annual descaling.", "Annual energy savings with tankless: roughly 20–35% of your hot water heating cost."] },
      { type: "h2", text: "When tankless makes sense" },
      { type: "ul", items: ["Larger households (4+ people) with overlapping showers and laundry.", "Homes where floor space is at a premium.", "Long-term homeowners who'll recoup the upfront cost over 10+ years.", "Anyone planning a major reno where gas and venting are already being touched."] },
      { type: "h2", text: "When a tank is still the smart pick" },
      { type: "ul", items: ["Tight budget — you need hot water back today.", "Smaller households with predictable usage.", "Older homes with limited gas line capacity.", "Rental properties where ROI math doesn't pencil out."] },
      { type: "h2", text: "Get a real quote, not a sales pitch" },
      { type: "p", text: "We've installed both across every city in Niagara — and we'll tell you straight which one fits your home and your budget. Call 289-488-1007 for a free water heater consultation." },
    ],
  },
  {
    slug: "basement-flooding-st-catharines-spring",
    title: "Basement Flooding in St. Catharines: Why Spring is the Worst (and How to Be Ready)",
    excerpt: "From snowmelt to spring storms, St. Catharines basements take a beating in March and April. Here's how to keep yours dry.",
    metaDescription: "Prevent basement flooding in St. Catharines. Sump pump tips, backup options, and emergency response from Ottr Plumr Plumbing & Heating.",
    city: "St. Catharines",
    citySlug: "st-catharines",
    service: "Sump Pumps",
    serviceSlug: "sump-pumps",
    publishedAt: "2025-10-28",
    readMinutes: 5,
    body: [
      { type: "p", text: "St. Catharines homes — especially in older neighbourhoods like Western Hill, Glenridge, and Merritton — are vulnerable to basement flooding every spring. The combination of melting snow, saturated ground, and heavy April rains pushes the local water table up and overwhelms unprepared sump systems." },
      { type: "h2", text: "Why spring floods St. Catharines basements" },
      { type: "p", text: "Two things happen in March and April: the frozen ground thaws and can no longer absorb water, and our spring storm cycle dumps an enormous amount of rain in short bursts. If your sump pump is undersized, your discharge line is clogged, or you don't have a battery backup — you're rolling the dice." },
      { type: "h2", text: "5 things to do before April" },
      { type: "ul", items: ["Test your sump pump now — pour a bucket of water in the pit and confirm the float trips and the pump fully drains it.", "Inspect the discharge line for cracks, ice, or clogs and make sure it points well away from your foundation.", "Add a battery backup pump — 80% of basement floods happen during storms that knock out power.", "Install a water alarm in the pit so you get an alert before it overflows.", "Replace any sump pump older than 8 years — they almost always fail under load, not at rest."] },
      { type: "h2", text: "Already flooding? Here's what to do" },
      { type: "p", text: "If you have water coming in right now: cut power to the basement at the breaker before stepping in. Move valuables to higher ground. Then call us — we run 24/7 emergency service and can usually have a tech in St. Catharines within the hour." },
    ],
  },
  {
    slug: "furnace-not-heating-niagara-falls",
    title: "Furnace Not Heating in Niagara Falls? 7 Things to Check Before You Call",
    excerpt: "Before you call a no-heat emergency, run through this 5-minute homeowner checklist. Half the time, you can fix it yourself.",
    metaDescription: "Furnace not heating in Niagara Falls? Try these 7 quick fixes first. If you still need help, Ottr Plumr offers 24/7 emergency furnace service.",
    city: "Niagara Falls",
    citySlug: "niagara-falls",
    service: "Heating Systems",
    serviceSlug: "heating-systems",
    publishedAt: "2025-10-15",
    readMinutes: 6,
    body: [
      { type: "p", text: "Furnace stopped blowing warm air? Don't panic — and don't necessarily book an after-hours service call yet. Niagara Falls homeowners can often resolve a no-heat issue in five minutes with this checklist before paying for an emergency dispatch." },
      { type: "h2", text: "1. Check the thermostat" },
      { type: "p", text: "Make sure it's set to HEAT, the temperature is set above the room temperature, and the batteries (if applicable) aren't dead. It sounds obvious — it's the #1 cause of \"my furnace isn't working\" calls." },
      { type: "h2", text: "2. Replace the air filter" },
      { type: "p", text: "A clogged filter can cause your furnace to overheat and shut down on a safety. If your filter looks grey or you can't remember the last time you changed it — change it now and try again." },
      { type: "h2", text: "3. Check the breaker and furnace switch" },
      { type: "p", text: "Most furnaces have a regular wall switch (looks like a light switch) on or near the unit. Make sure it's ON. Then check your electrical panel for a tripped breaker." },
      { type: "h2", text: "4. Confirm gas is on" },
      { type: "p", text: "Check that the gas valve at the furnace is in the open position and that other gas appliances in your home are working." },
      { type: "h2", text: "5. Look for a blinking diagnostic light" },
      { type: "p", text: "Most modern furnaces have an LED behind a small viewing window that blinks an error code. Count the blinks and look up your model — it'll tell you exactly what's wrong." },
      { type: "h2", text: "6. Check the condensate drain" },
      { type: "p", text: "High-efficiency furnaces can shut down if the condensate line is clogged. If you see water around the unit, this is likely the cause." },
      { type: "h2", text: "7. Cycle the power" },
      { type: "p", text: "Turn the furnace switch off, wait 30 seconds, and turn it back on. Sometimes the control board just needs a reset." },
      { type: "h2", text: "Still no heat?" },
      { type: "p", text: "Call us at 289-488-1007. We respond to no-heat emergencies in Niagara Falls 24/7, and we'll always quote the repair before we start work." },
    ],
  },
  {
    slug: "clogged-drain-niagara-diy-vs-pro",
    title: "Clogged Drain in Niagara: DIY Fixes vs When to Call a Plumber",
    excerpt: "Some clogs you can clear with a plunger. Others need a camera and a snake. Here's how to tell the difference before you make it worse.",
    metaDescription: "Clogged drain in the Niagara Region? Learn which DIY fixes work, what to avoid (chemical drain cleaners!), and when to call Ottr Plumr.",
    city: "Niagara Region",
    service: "Residential Plumbing",
    serviceSlug: "residential-plumbing",
    publishedAt: "2025-10-02",
    readMinutes: 5,
    body: [
      { type: "p", text: "A slow drain doesn't always mean a service call. But the wrong DIY fix — especially harsh chemical drain cleaners — can damage your pipes and turn a $200 problem into a $2,000 one. Here's our honest field guide." },
      { type: "h2", text: "Try these DIY fixes first" },
      { type: "ul", items: ["Plunger — works on toilets, tubs, and sinks. Cover the overflow with a wet rag for a better seal.", "Boiling water + dish soap — great for grease clogs in kitchen sinks.", "Baking soda + vinegar + hot water flush — gentle and pipe-safe.", "Plastic drain snake (the cheap zip kind) — surprisingly effective on hair clogs in bathroom sinks and tubs."] },
      { type: "h2", text: "Avoid chemical drain cleaners" },
      { type: "p", text: "Drano and similar products are caustic. They can soften PVC, corrode metal pipes over time, and create a hazardous situation for any plumber who has to open the line afterward. Skip them." },
      { type: "h2", text: "When to call a plumber" },
      { type: "ul", items: ["Multiple drains backed up at once — points to a main line clog.", "Sewage smell or gurgling sounds — possible vent or sewer issue.", "Recurring clogs in the same spot — there's a deeper cause your plunger can't reach.", "Water backing up into a different fixture when you flush — a serious main line problem.", "Standing water that won't move after a thorough plunge."] },
      { type: "h2", text: "What we do" },
      { type: "p", text: "For tough clogs we run a camera to see exactly what's happening — roots, grease buildup, broken pipes, or foreign objects — then clear it with the right tool: snake, hydro-jet, or repair if needed. No guessing, no upsell. Call 289-488-1007 across Niagara." },
    ],
  },
  {
    slug: "annual-plumbing-maintenance-checklist-niagara",
    title: "Annual Plumbing Maintenance Checklist for Niagara Homeowners",
    excerpt: "An hour of maintenance each year saves thousands in emergency repairs. Here's what every Niagara homeowner should check.",
    metaDescription: "Annual home plumbing maintenance checklist for Niagara Region homeowners. Prevent leaks, clogs, and water heater failures with these simple steps.",
    city: "Niagara Region",
    service: "Repairs & Diagnostics",
    serviceSlug: "repairs-diagnostics",
    publishedAt: "2025-09-20",
    readMinutes: 5,
    body: [
      { type: "p", text: "We see the same preventable failures over and over: water heaters that rusted through, sump pumps that seized up, valves that won't close when they're needed most. An hour of preventive maintenance every year keeps your plumbing system running and saves you from 3 a.m. emergency calls." },
      { type: "h2", text: "Spring (March – May)" },
      { type: "ul", items: ["Test your sump pump and check the discharge line.", "Inspect outdoor spigots for freeze damage and reattach garden hoses.", "Check washing machine hoses for bulges or cracks — replace every 5 years.", "Walk the basement looking for any signs of moisture or staining."] },
      { type: "h2", text: "Summer (June – August)" },
      { type: "ul", items: ["Drain and flush your water heater to remove sediment.", "Inspect the anode rod (replace if more than 50% consumed).", "Check toilet flappers and fill valves — silent leaks waste thousands of litres per year.", "Test all main shutoff valves to ensure they still turn."] },
      { type: "h2", text: "Fall (September – November)" },
      { type: "ul", items: ["Book a furnace tune-up before heating season.", "Disconnect outdoor hoses and shut off interior valves to outdoor spigots.", "Insulate any exposed pipes in unheated areas.", "Test smoke and CO detectors — especially near gas appliances."] },
      { type: "h2", text: "Winter (December – February)" },
      { type: "ul", items: ["On extreme cold nights, drip faucets on exterior walls.", "Open cabinets under sinks on exterior walls to circulate warm air.", "Know where your main shutoff valve is — and make sure it works.", "Keep the thermostat at 18°C (65°F) minimum, even when away."] },
      { type: "h2", text: "Want a pro to do it for you?" },
      { type: "p", text: "Ottr Plumr offers annual maintenance plans across Niagara — one visit, one flat price, every check on this list and more. Call 289-488-1007 to set yours up." },
    ],
  },
  {
    slug: "hard-water-niagara-what-to-do",
    title: "Hard Water in Niagara: Why It's So Bad Here (and What to Do About It)",
    excerpt: "Niagara has some of the hardest municipal water in Ontario. Here's what it's doing to your pipes, water heater, and fixtures — and how to fix it.",
    metaDescription: "Hard water in the Niagara Region is damaging your plumbing and appliances. Learn the causes, signs, and solutions from Ottr Plumr — your local licensed plumber.",
    city: "Niagara Region",
    service: "Residential Plumbing",
    serviceSlug: "residential-plumbing",
    publishedAt: "2026-01-08",
    readMinutes: 7,
    body: [
      { type: "p", text: "If you've lived in Niagara for any length of time, you've noticed it: white crusty buildup around your faucets, spots on your dishes, shampoo that won't lather properly, and a water heater that sounds like a popcorn maker. That's hard water — and Niagara has a lot of it." },
      { type: "h2", text: "Why Niagara water is so hard" },
      { type: "p", text: "Niagara Region's drinking water is drawn from Lake Ontario and Lake Erie, both fed by water that's travelled through the limestone-heavy geology of the Great Lakes basin. That journey loads the water with dissolved calcium and magnesium — the minerals that cause hardness. Most municipalities in Niagara measure between 140–200 mg/L of hardness, well above the 120 mg/L threshold considered \"very hard\" by Health Canada." },
      { type: "h2", text: "What hard water does to your home" },
      { type: "ul", items: ["Scale buildup inside water heater tanks — reduces efficiency by up to 30% and cuts lifespan by years.", "Clogged showerheads and aerators — reduced flow and pressure over time.", "Stained sinks, tubs, and toilets — white or yellow mineral deposits that are hard to remove.", "Shortened appliance lifespan — dishwashers, washing machines, and coffee makers all suffer.", "Dry skin and hair — hard water leaves a mineral film that strips moisture.", "Higher energy bills — a scaled water heater works harder to heat the same water."] },
      { type: "h2", text: "Signs you have a hard water problem" },
      { type: "ul", items: ["White chalky deposits around faucets, showerheads, and the kettle.", "Spots on glassware and dishes even after washing.", "Soap and shampoo that don't lather well.", "A water heater making rumbling or popping sounds (that's scale flaking off the element).", "Reduced water pressure at fixtures over time."] },
      { type: "h2", text: "Solutions — from simple to permanent" },
      { type: "h3", text: "Descaling appliances (short-term)" },
      { type: "p", text: "White vinegar dissolves calcium deposits on showerheads, kettle elements, and faucet aerators. Soak overnight and scrub clean. This treats the symptom, not the cause — but it's free and immediate." },
      { type: "h3", text: "Water softener (best long-term solution)" },
      { type: "p", text: "A whole-home ion-exchange water softener replaces calcium and magnesium with sodium, delivering soft water to every tap. Installed at the main water entry point, a properly sized softener protects your entire plumbing system and all appliances. Typical installed cost in Niagara: $2,500–$4,500 depending on the unit and home size. It pays for itself in extended appliance life and energy savings within 5–7 years." },
      { type: "h3", text: "Tankless water heater with annual descaling" },
      { type: "p", text: "If you have or are considering a tankless water heater, annual descaling (a vinegar flush through the heat exchanger) is essential in Niagara's hard water. Without it, scale builds up on the heat exchanger and the unit will fail within a few years. We offer descaling service — call 289-488-1007 to schedule." },
      { type: "h2", text: "Talk to a local plumber before you buy" },
      { type: "p", text: "Water softener sizing matters — too small and it won't keep up, too large and it wastes salt and water during regeneration cycles. We assess your household size, water usage, and incoming hardness level before recommending a unit. Call 289-488-1007 for a free consultation across the Niagara Region." },
    ],
  },
  {
    slug: "sump-pump-buying-guide-niagara",
    title: "Sump Pump Buying Guide for Niagara Basements (2026)",
    excerpt: "Not all sump pumps are built for Niagara's spring melt and storm season. Here's what to look for — and what will leave you with a flooded basement.",
    metaDescription: "Choosing a sump pump for a Niagara Region home? This guide covers pump types, sizing, battery backup, and installation tips from Ottr Plumr.",
    city: "Niagara Region",
    service: "Sump Pumps",
    serviceSlug: "sump-pumps",
    publishedAt: "2026-01-22",
    readMinutes: 8,
    body: [
      { type: "p", text: "Niagara basements take a beating every spring. Snowmelt, saturated ground, and the region's clay-heavy soil all push water toward foundations — and if your sump pump isn't up to the job, you'll know about it at the worst possible time. Here's everything you need to know before buying." },
      { type: "h2", text: "Types of sump pumps" },
      { type: "h3", text: "Pedestal pump" },
      { type: "p", text: "The motor sits above the pit on a pedestal, with just the impeller submerged. Easier to service, cheaper to buy, and the motor stays dry. Downside: noisier and less powerful than a submersible. Fine for light-duty applications but not ideal for Niagara's spring volumes." },
      { type: "h3", text: "Submersible pump" },
      { type: "p", text: "The entire unit sits submerged in the pit. Quieter, more powerful, and better at handling high water volumes. This is what we install in most Niagara homes. Look for cast iron construction over plastic — it dissipates heat better and lasts longer." },
      { type: "h2", text: "What size do you need?" },
      { type: "p", text: "Most Niagara homes need a 1/3 or 1/2 HP submersible pump. If you have a large basement, a high water table (common in Welland, Port Colborne, and lakeshore areas), or a history of heavy spring flooding, go to 3/4 HP. Undersizing is the most common mistake — a pump that can't keep up with inflow will run continuously and burn out." },
      { type: "h2", text: "Battery backup — not optional in Niagara" },
      { type: "p", text: "The worst basement floods happen during storms — and storms knock out power. A battery backup system kicks in automatically when the main pump fails or loses power, typically running for 5–8 hours on a full charge. In Niagara, we consider this essential, not optional. The cost of a battery backup ($800–$1,500 installed) is nothing compared to a flooded basement." },
      { type: "h2", text: "What to look for when buying" },
      { type: "ul", items: ["Cast iron construction — not plastic. Cast iron handles heat better and lasts 15+ years vs 5–8 for plastic.", "Automatic float switch — vertical float switches are more reliable than tethered floats in narrow pits.", "1/2 HP minimum for most Niagara homes.", "Check valve on the discharge line — prevents backflow when the pump shuts off.", "Alarm system — a high-water alarm gives you warning before the pit overflows."] },
      { type: "h2", text: "Brands we trust" },
      { type: "p", text: "We install Zoeller, Wayne, and Liberty pumps — all proven performers in hard-water environments like Niagara. We stay away from big-box store house brands; they're built to a price point, not a performance standard." },
      { type: "h2", text: "When to replace your existing pump" },
      { type: "ul", items: ["It's more than 8–10 years old.", "It runs continuously or cycles on and off rapidly.", "It makes grinding or rattling sounds.", "It failed or struggled during the last spring melt.", "You've had any flooding despite the pump running."] },
      { type: "h2", text: "Get it installed right" },
      { type: "p", text: "A sump pump is only as good as its installation — the pit size, discharge line routing, check valve, and backup system all matter. Ottr Plumr installs sump pumps across every city in Niagara. Call 289-488-1007 for a free quote." },
    ],
  },
  {
    slug: "sewer-lateral-root-intrusion-niagara",
    title: "Tree Root Intrusion in Niagara Sewer Lines: What Every Homeowner Should Know",
    excerpt: "Root intrusion is the #1 cause of sewer backups in older Niagara neighbourhoods. Here's how to spot it, fix it, and prevent it from coming back.",
    metaDescription: "Tree roots in your sewer line? This is the most common cause of sewer backups in older Niagara homes. Ottr Plumr explains the causes, fixes, and costs.",
    city: "Niagara Region",
    service: "Drain Cleaning",
    serviceSlug: "drain-cleaning",
    publishedAt: "2026-02-05",
    readMinutes: 7,
    body: [
      { type: "p", text: "If your basement floor drain backs up every spring, or your toilets gurgle when you run the washing machine, there's a good chance you have tree roots in your sewer lateral. In Niagara's older neighbourhoods — Crowland and Dain City in Welland, Western Hill and Merritton in St. Catharines, Chippawa in Niagara Falls — this is the single most common cause of sewer problems we deal with." },
      { type: "h2", text: "Why Niagara is especially prone to root intrusion" },
      { type: "p", text: "Most homes built before 1980 in the Niagara Region have clay tile or Orangeburg sewer laterals — the pipe that runs from your house to the municipal main under the street. These pipes were installed in short sections joined with loose-fitting collars, which were fine when the pipes were new. Over decades, those joints shift and separate slightly, and tree roots — which are drawn to the moisture and nutrients in sewer lines — find those gaps and grow in." },
      { type: "h2", text: "Signs you have root intrusion" },
      { type: "ul", items: ["Slow drains throughout the house — not just one fixture.", "Gurgling sounds from toilets when you run other drains.", "Sewage smell in the basement or backyard.", "Basement floor drain or toilet backing up during heavy rain or spring melt.", "Recurring clogs that keep coming back despite snaking."] },
      { type: "h2", text: "How we diagnose it" },
      { type: "p", text: "The only way to confirm root intrusion is a sewer camera inspection. We push a camera through the cleanout (or through the toilet if there's no cleanout) and view the inside of the pipe in real time. We can see root masses, cracked sections, offset joints, and bellies — and we record the footage so you can see exactly what's in your line. Most camera inspections take 20–30 minutes." },
      { type: "h2", text: "Treatment options" },
      { type: "h3", text: "Cable cutting (snaking)" },
      { type: "p", text: "A sectional drain machine with a root-cutting head will grind through root masses and restore flow. This is the right immediate fix for a blocked line. It won't remove all root material, and roots will regrow — typically within 1–3 years on an untreated line." },
      { type: "h3", text: "Hydro-jetting" },
      { type: "p", text: "High-pressure water jetting at 3,500–4,000 PSI scours the pipe walls and removes root matter more thoroughly than cable cutting. Combined with a foaming root inhibitor treatment, this can extend the interval between cleanings significantly." },
      { type: "h3", text: "Trenchless lining (CIPP)" },
      { type: "p", text: "If the pipe has structural damage — offset joints, cracked sections, or collapse — the permanent fix is cured-in-place pipe (CIPP) lining. A resin-saturated liner is pulled through the existing pipe and cured in place, creating a new seamless pipe inside the old one. No digging, no disruption to the yard. This is increasingly our recommended solution for Niagara clay laterals in poor condition." },
      { type: "h3", text: "Open-cut replacement" },
      { type: "p", text: "When the pipe is too far gone for lining — collapsed sections, severe grade issues, or Orangeburg that's turned to mush — open-cut replacement is the answer. We excavate, remove the old pipe, and install new PVC. More disruptive and more expensive, but it solves the problem permanently." },
      { type: "h2", text: "What does it cost?" },
      { type: "h2", text: "Prevention" },
      { type: "p", text: "If you have clay tile laterals and mature trees in your yard, annual maintenance jetting plus root inhibitor is the most cost-effective long-term strategy. We offer annual maintenance plans across Niagara — call 289-488-1007 to get set up." },
    ],
  },
  {
    slug: "niagara-plumbing-rebates-subsidies-2026",
    title: "Niagara Region Plumbing Rebates and Subsidies in 2026",
    excerpt: "There's real money available for Niagara homeowners who upgrade their plumbing — sewer laterals, water heaters, and more. Here's what's available and how to apply.",
    metaDescription: "Niagara Region plumbing rebates and subsidies in 2026 — basement flooding protection, sewer lateral programs, and water efficiency incentives. From Ottr Plumr.",
    city: "Niagara Region",
    service: "Sump Pumps",
    serviceSlug: "sump-pumps",
    publishedAt: "2026-02-19",
    readMinutes: 6,
    body: [
      { type: "p", text: "Most Niagara homeowners don't know there's money on the table for plumbing upgrades. Between municipal basement flooding programs, regional water efficiency rebates, and provincial incentives, you could recover a significant chunk of the cost of a sump pump, sewer lateral repair, or water heater upgrade. Here's what's available in 2026." },
      { type: "h2", text: "Niagara Region Basement Flooding Protection Subsidy" },
      { type: "p", text: "The Niagara Region offers a Basement Flooding Protection Subsidy Program for eligible homeowners. The program provides subsidies for flood protection measures including sump pump installation with battery backup, backwater valve installation, and window well covers. Subsidies can cover up to 50% of eligible costs to a maximum of $2,800 per property. Applications are available through the Niagara Region's website — your contractor needs to be licensed and the work must be permitted." },
      { type: "h2", text: "Municipal sewer lateral programs" },
      { type: "p", text: "Several Niagara municipalities have their own programs for homeowners dealing with aging sewer laterals. The City of Welland, St. Catharines, and Niagara Falls all periodically offer low-interest loans or grants for sewer lateral replacement on private property. These programs open and close based on funding — check with your municipality's public works department or call us and we'll help you navigate what's currently available." },
      { type: "h2", text: "Canada Greener Homes Grant (federal)" },
      { type: "p", text: "The federal Canada Greener Homes program offers rebates for energy efficiency upgrades including high-efficiency water heaters (heat pump water heaters and qualifying tankless units). Rebates of up to $1,000 are available for qualifying water heater installations. You need a pre-retrofit EnerGuide assessment before the work and a post-retrofit assessment after — we can help coordinate this." },
      { type: "h2", text: "Ontario Electricity Rebates for Heat Pump Water Heaters" },
      { type: "p", text: "Heat pump water heaters qualify for rebates through several Ontario programs. These units are highly efficient (using electricity to move heat rather than generate it) and can dramatically reduce your hot water heating costs. Combined with the federal Greener Homes rebate, the payback period is significantly shortened." },
      { type: "h2", text: "How to access these programs" },
      { type: "ul", items: ["Check the Niagara Region website (niagararegion.ca) for the current Basement Flooding Protection Subsidy application.", "Contact your municipality's public works department for any local sewer lateral programs.", "Visit canada.ca/greener-homes for the federal program — pre-registration is required before any work begins.", "Call us before booking any subsidized work — we're familiar with the permit and documentation requirements for each program and can help you avoid mistakes that disqualify your application."] },
      { type: "h2", text: "We work with all of these programs" },
      { type: "p", text: "Ottr Plumr is a licensed plumbing contractor across the Niagara Region and our work meets the requirements of all the programs listed above. If you're considering a sump pump, backwater valve, sewer lateral repair, or water heater upgrade, call us first — we'll let you know which programs apply and help you get the paperwork right. Call 289-488-1007." },
    ],
  },
  {
    slug: "repipe-niagara-home-galvanized-pex-copper",
    title: "Re-piping a Niagara Home: Galvanized vs PEX vs Copper",
    excerpt: "Got low water pressure, rust-coloured water, or pinhole leaks? It might be time to repipe. Here's what you need to know about your options in Niagara.",
    metaDescription: "Considering re-piping your Niagara home? Compare galvanized, copper, and PEX options — costs, lifespan, and which is right for your house. From Ottr Plumr.",
    city: "Niagara Region",
    service: "Residential Plumbing",
    serviceSlug: "residential-plumbing",
    publishedAt: "2026-03-04",
    readMinutes: 8,
    body: [
      { type: "p", text: "Niagara has a lot of older housing stock — century homes in St. Catharines and Niagara-on-the-Lake, post-war builds in Welland and Port Colborne, 1960s and 70s subdivisions throughout the region. Many of these homes still have their original galvanized steel supply pipes, and those pipes are living on borrowed time." },
      { type: "h2", text: "Signs you need to repipe" },
      { type: "ul", items: ["Low water pressure throughout the house — not just at one fixture.", "Rusty or brown-tinted water, especially first thing in the morning.", "Frequent pinhole leaks or burst pipes.", "Water that tastes metallic.", "Visible corrosion or mineral buildup on exposed pipes.", "Your home was built before 1970 and you've never replaced the supply lines."] },
      { type: "h2", text: "Understanding your pipe options" },
      { type: "h3", text: "Galvanized steel — the old standard" },
      { type: "p", text: "Galvanized steel was the go-to supply pipe material from the early 1900s through the 1960s. It's zinc-coated steel, which provides corrosion resistance — but only for so long. After 40–70 years, the zinc coating fails, the interior rusts, and mineral deposits narrow the pipe bore significantly. Low pressure, rusty water, and leaks are the result. If you have galvanized, it needs to come out." },
      { type: "h3", text: "Copper — the long-term standard" },
      { type: "p", text: "Copper became the dominant supply pipe material after World War II and remains excellent. It's durable (50–70 year lifespan), biologically inert, resistant to corrosion, and compatible with Niagara's hard water. The downside: cost. Copper is significantly more expensive than PEX, both in materials and labour (it requires soldering). In Niagara's hard water environment, copper can experience accelerated pitting corrosion — a good plumber will account for this in the installation." },
      { type: "h3", text: "PEX — the modern choice" },
      { type: "p", text: "Cross-linked polyethylene (PEX) tubing has largely replaced copper for new residential work and repiping over the last 15 years. It's flexible (reducing the number of fittings needed), freeze-resistant, immune to corrosion, and significantly less expensive than copper. PEX can be run in long continuous runs from a central manifold to each fixture — called a home-run system — which virtually eliminates in-wall joints and the leaks they cause. Lifespan is estimated at 50+ years. This is what we use for most repiping projects in Niagara." },
      { type: "h2", text: "Cost comparison (Niagara averages)" },
      { type: "ul", items: ["Copper repipe (average 3-bed home): $12,000–$18,000 supplied and installed.", "PEX repipe (average 3-bed home): $7,000–$12,000 supplied and installed.", "Partial repipe (one floor or one branch): $2,500–$5,000.", "Costs vary based on home size, number of fixtures, and access complexity."] },
      { type: "h2", text: "What the process looks like" },
      { type: "p", text: "A full repipe typically takes 2–3 days for an average home. We work room by room, cutting small access holes in walls and ceilings where needed to run new pipe. New shutoff valves are installed at every fixture. Once the new pipe is in and tested, we patch the drywall (or leave it for your drywaller — your call). Water is only off for a few hours during the final connection and pressure test." },
      { type: "h2", text: "Get a repipe quote" },
      { type: "p", text: "If you're dealing with any of the symptoms above, the sooner you address it the better — a failed galvanized pipe inside a wall causes far more damage than the repipe itself. Ottr Plumr provides free repipe assessments across the Niagara Region. Call 289-488-1007." },
    ],
  },
];

export const getPostBySlug = (slug?: string) => POSTS.find((p) => p.slug === slug);
